---
- name: Verify
  hosts: all
  tasks:
    - name: Check if Home Assistant user exists
      ansible.builtin.command: id hass
      register: user_check
      failed_when: user_check.rc != 0
      changed_when: false

    - name: Check if compose directory exists
      ansible.builtin.stat:
        path: /srv/homeassistant/compose
      register: compose_dir_check
      failed_when: not compose_dir_check.stat.exists

    - name: Check if data directory exists
      ansible.builtin.stat:
        path: /srv/homeassistant/data
      register: data_dir_check
      failed_when: not data_dir_check.stat.exists

    - name: Check if Docker Compose file exists
      ansible.builtin.stat:
        path: /srv/homeassistant/compose/docker-compose.yml
      register: compose_file_check
      failed_when: not compose_file_check.stat.exists

    - name: Validate Docker Compose file
      ansible.builtin.command:
        cmd: docker compose -f /srv/homeassistant/compose/docker-compose.yml config
      register: compose_validation
      failed_when: compose_validation.rc != 0
      changed_when: false
